version: '3.8'

services:
    web:
        build: .
        container_name: OpenMobi-DanielJablonski
        volumes:
            - .:/var/www
        environment:
            - APP_ENV=dev
        ports:
            - 8005:80